### ISSUE TITLE
agrest-parent depends on Bootique BOM 2.0.B1-SNAPSHOT version

### ISSUE THREAD

**Issue by scali** [bootique-examples/bootique-linkrest-demo#5]
Hi,

When I try to install or package (`mvn package`) the demo of bootique-agrest-demo, maven found a dependency that cannot be found.

It's seems that it could be related with the recent change of repository (https://groups.google.com/g/bootique-user/c/2lHmIJ7F39I) as Bootique BOM 2.0.B1-SNAPSHOT artifacts are not in the new repository : https://oss.sonatype.org/content/repositories/snapshots/

Is there is a way to override transitive dependency to force Agrest to use Bootique BOM 2.0.B1 instead of its SNAPSHOT version ?

**Comment by andrus** [comment]
This was fixed recently per https://github.com/agrestio/agrest/issues/487 , new releases of Agrest where posted. Bootique v. `2.0.RC1-SNAPSHOT` contains the fix. So until RC1 is released, you can do the following:

1. Ensure you are on the branch [2.x](https://github.com/bootique-examples/bootique-agrest-demo/tree/2.x) of the demo project.

2. Add our SNAPSHOT repo to the POM
```
<repositories>
    <repository>
        <id>bootique-snapshots</id>
        <url>https://oss.sonatype.org/content/repositories/snapshots</url>
        <releases>
            <enabled>false</enabled>
        </releases>
        <snapshots>
            <enabled>true</enabled>
        </snapshots>
    </repository>
</repositories>
```
3. Switch Bootique version in the POM to `2.0.RC1-SNAPSHOT`

This should fix the issue.

**Comment by scali** [comment]
Thanks !

To make it works I also had to update `agrest` dependency in the demo project from :

```
<dependency>
    <groupId>io.agrest</groupId>
    <artifactId>agrest</artifactId>
    <version>4.1</version>
</dependency>
```
to :

```
<dependency>
    <groupId>io.agrest</groupId>
    <artifactId>agrest-engine</artifactId>
    <version>4.6-SNAPSHOT</version>
</dependency>
```
